version: '3.9'
services:
  gamebuddy-svc:
    build: ./gamebuddy-svc
    ports:
        - "8080:8080"
    depends_on:
      - repository-svc

  repository-svc:
    build: ./repository-svc
    ports:
      - "8081:8081"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
